version: 2

models:
  - name: test_cwv_prod
    description: 'TEST quality data cwv_prod'
    columns:
      - name: psi
        tests:
          - not_null
      - name: device
        tests:
          - accepted_values:
              values: ['mobile', 'desktop']
          - not_null
      - name: date
      - name: tti
      - name: categorie
      - name: url
